/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.main;
import client.RunClient;

import com.raven.component.Menu;
import com.raven.component.SubForm1;
import com.raven.component.SubForm2;
import com.raven.component.SubForm3;
import com.raven.component.SubForm4;
import com.raven.component.Tutorial;
import com.raven.event.EventMenu;

import java.awt.Color;
import java.awt.Desktop;
import java.net.URI;

/**
 *
 * @author RAVEN
 */
public class Event extends javax.swing.JFrame {


/**
     * Creates new form Main
     */
        public Event() {
        initComponents();
        getContentPane().setBackground(new Color(236, 236, 236));
        MainProgram.getInstance().setSlideShow(slideshow);
        EventMenu event = new EventMenu() {
            @Override
            public void selected(int index) {
                slideshow.slideTo(index + 1);
              
            }
        };
        Menu menu = new Menu();
        menu.initMenu(event);
        slideshow.initSlideshow(menu, new SubForm1("Event1"), new SubForm2("Event2"), new SubForm3("Event3"), new SubForm4("Event4"), new Tutorial("Exit"));


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pictureBox1 = new com.raven.swing.PictureBox();
        slideshow = new com.raven.swing.slideshow.Slideshow();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pictureBox1.setImage(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/background.jpg"))); // NOI18N
        pictureBox1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pictureBox1.add(slideshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 605));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/4.png"))); // NOI18N
        jButton1.setText("BackToMainMenu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pictureBox1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 190, 50));

        jButton2.setText("Homepage");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pictureBox1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 590, 170, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(pictureBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(pictureBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            RunClient.closeScene(RunClient.SceneName.EVENT);                                              

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   Desktop desktop = Desktop.getDesktop();

        String homepageUrl = "https://www.facebook.com/gomoku.board.game?locale=vi_VN";

        try {
            URI uri = new URI(homepageUrl);
            desktop.browse(uri);
        } catch (Exception e) {
            e.printStackTrace();
        }    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Event().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.raven.swing.PictureBox pictureBox1;
    private com.raven.swing.slideshow.Slideshow slideshow;
    // End of variables declaration//GEN-END:variables
}
